### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

### ISSUE THREAD

**Issue by higuita** [psomas/ketchup#2]
Hi

trying to checkout a clean 3.0.3 tree  i'm getting this with the latest git
# ketchup 3

None -> 3.0.3
Traceback (most recent call last):
  File "/usr/local/sbin/ketchup", line 967, in <module>
    transform(a, b)
  File "/usr/local/sbin/ketchup", line 703, in transform
    a = install_nearest(base(b))
  File "/usr/local/sbin/ketchup", line 660, in install_nearest
    t += '.0'
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

i'm not a programmer and dont even know basic python, but google tells me that this should fix the issue until its fixed in the git:

 if t >= 3:
    t = str(t)   <--- add this
    t += '.0' 

thanks for ketchup

**Comment by psomas** [comment]
Are you sure you've pulled the updates from the linux-3 branch? This was fixed about a month ago.

**Comment by higuita** [comment]
Hi 

On Wed, 17 Aug 2011 15:06:41 -0700, psomas
reply@reply.github.com
wrote:

> Are you sure you've pulled the updates from the linux-3 branch? This
> was fixed about a month ago.

```
strange... i have done what i learned about git (very little!!) :) 

i update doing this:
```

~/build/ketchup/$ git fetch
~/build/ketchup/$ git rebase origin
Current branch linux-3 is up to date.

```
yet, as you said it was already fixed, i tried to confirm that it
```

was OK:

~/build/ketchup/$ git status ketchup

# On branch linux-3

# Your branch is behind 'origin/linux-3' by 3 commits, and can be fast-forwarded.

#
nothing to commit (working directory clean)

```
So looks you are right and i dont know why, but the fetch+
```

rebase didnt got all changes, but didnt warned me about it

```
i tried the git pull to see if made any difference and it
```

worked:

~/build/ketchup/$ git pull  
Updating 3154e2e..ad84385
Fast-forward
 ketchup |    8 ++++----
 1 files changed, 4 insertions(+), 4 deletions(-)

~/build/ketchup/$ git status 

# On branch linux-3

nothing to commit (working directory clean)

```
so i really dont understand why it failed, but i will
```

read better the man pages and web howto

```
So sorry about the noise and look like i still have alot
```

to learn how git works :)

thanks for the help and for the ketchup

## higuita

Naturally the common people don't want war... but after all it is the
leaders of a country who determine the policy, and it is always a 
simple matter to drag the people along, whether it is a democracy, or
a fascist dictatorship, or a parliament, or a communist dictatorship.
Voice or no voice, the people can always be brought to the bidding of
the leaders. That is easy. All you have to do is tell them they are 
being attacked, and denounce the pacifists for lack of patriotism and
exposing the country to danger.  It works the same in every country.
           -- Hermann Goering, Nazi and war criminal, 1883-1946
