### ISSUE TITLE
linux-3 branch need update to new sign files

### ISSUE THREAD

**Issue by higuita** [psomas/ketchup#3]
# ketchup 3

None -> 3.1.4
Unpacking linux-3.0.3.tar.bz2
Applying patch-3.0.3.bz2 -R
Applying patch-3.1.bz2
Check if GPG key is available...
Downloading patch-3.1.4.bz2.sign
--2011-11-30 03:01:18--  http://www.kernel.org/pub/linux/kernel/v3.0/patch-3.1.4.bz2.sign
Resolving www.kernel.org (www.kernel.org)... 149.20.4.69
Connecting to www.kernel.org (www.kernel.org)|149.20.4.69|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2011-11-30 03:01:19 ERROR 404: Not Found.
using the current  linux-3 branch (SHA-1 ad84385f48ccf8c93374043f15342148e695ae02) i get this trying to get a new tree:

ketchup: signature download failed
Check if GPG key is available...
Downloading patch-3.1.4.bz2.sign
--2011-11-30 03:01:19--  http://www.kernel.org/pub/linux/kernel/v3.0/longterm/v3.1/patch-3.1.4.bz2.sign
Resolving www.kernel.org (www.kernel.org)... 149.20.4.69
Connecting to www.kernel.org (www.kernel.org)|149.20.4.69|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2011-11-30 03:01:19 ERROR 404: Not Found.

ketchup: signature download failed
ketchup: patch download failed

AFAIK,  now the uncompressed patches are the one signned, there are no more the different compression signatures, so ketchup needs to be updated

thanks
higuita.

**Comment by psomas** [comment]
It should be fixed now.

There are still some issues (patches and tarballs are still missing from kernel.org), and ketchup won't work for all kernel versions and 'transitions', but it should work ok for relatively new kernels (>=3.0),
